apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server-headless
  name: grpc-server-headless
  namespace: default
spec:
  clusterIP: "None"
  ports:
  - port: 5287
    protocol: TCP
    targetPort: 5287
  selector:
    app: grpc-server
